<div class="login-page">
    <div class="form">
        <form name="login" action="#" method="post" class="login-form">
            <input type="text" placeholder="Username" name="username">
            <input type="password" placeholder="Password" name="password">
            <input type="password" placeholder="Conferma Password" name="cpassword">
            <input type="email" placeholder="Email" name="email">
            <input type="submit" value="SignUp">
        </form>
    </div>
</div>
